defaults:
  - latent_world_model@architecture.config: cs2_small

architecture:
  _target_: mira.world_model.latent_world_model.LatentWorldModel
  _convert_: all

  config:
    _target_: mira.world_model.config.LatentWorldModelConfig
    actions: ${dataset.actions}
    video:
      _target_: mira.ml.image_config.ImageConfig
      height: 168
      width: 308
      channels: 3
      timesteps: 16
      fps: 8
    codec_checkpoint: null
    latent_mean_std: null

    patch_size: 1
    n_register_tokens: 0
    attention_gating: true
    n_context_frames: 8
    dropout_action_prob: 0.1
    max_mouse_movement: 180.0
    learned_temporal_pool: true
    causal: true
    use_codec_posterior_mean: true
    activation_checkpointing: true
    ada_attn_ln: true
    psd_loss_prob: 0.0
    psd_weight: 0.0
    use_clean_past: true
